"""Build manuscript tables only from the frozen audited scientific artifacts.

Run in conda clrr. This neither evaluates models nor changes source results.
"""
from pathlib import Path
import csv
import hashlib
import json
from package_paper_pdftex import embed_paper_tables

ROOT = Path(__file__).resolve().parents[2]
OUT = (ROOT / 'docs/paper/paper_tables') if (ROOT / 'docs/paper').exists() else (ROOT / 'docs/paper_tables')
SOURCES = {
    'audit_a': 'outputs_rebuttal/metric_audit_20261002/full/all_verified_translation_scores.csv',
    'scores_b': 'outputs_rebuttal/followup_20261003/matched_inference_scores.csv',
    'bootstrap_b': 'outputs_rebuttal/followup_20261003/matched_inference_bootstrap.csv',
    'mechanisms': 'outputs_rebuttal/checkpoint_diagnostics_20261002/mechanism_summary.csv',
    'seeds': 'outputs_rebuttal/amis_confirmation_20261003/seed_scores.csv',
    'summary': 'outputs_rebuttal/amis_confirmation_20261003/seed_summary.csv',
    'deltas': 'outputs_rebuttal/amis_confirmation_20261003/paired_seed_deltas.csv',
    'bootstrap_c': 'outputs_rebuttal/amis_confirmation_20261003/paired_bootstrap24.csv',
    'trajectory': 'outputs_rebuttal/amis_confirmation_20261003/trajectory_summary.csv',
}


def read(relative):
    with (ROOT / relative).open(encoding='utf-8-sig', newline='') as stream:
        return list(csv.DictReader(stream))


def f(value, places=2):
    return f'{float(value):.{places}f}'


def tex(value):
    return str(value).replace('&', r'\&').replace('_', r'\_').replace('%', r'\%')


def table(name, columns, headers, rows, caption, wide=False):
    environment = 'table*' if wide else 'table'
    width = r'\textwidth' if wide else r'\columnwidth'
    header_line = ' & '.join(r'\textbf{' + header + '}' for header in headers)
    body = '\n'.join(' & '.join(str(v) for v in row) + r' \\' for row in rows)
    text = rf'''% Generated by scripts/revalidation/build_paper_tables.py; do not hand-edit numbers.
\begin{{{environment}}}[!ht]
\centering
\caption{{{caption}}}
\label{{tab:{name}}}
\renewcommand{{\arraystretch}}{{1.15}}
\resizebox{{{width}}}{{!}}{{%
\begin{{tabular}}{{{columns}}}
\toprule
{header_line} \\
\midrule
{body}
\bottomrule
\end{{tabular}}%
}}
\end{{{environment}}}
'''
    assert not any(ord(c)<32 and c!='\n' for c in text), name
    (OUT / f'{name}.tex').write_text(text, encoding='utf-8')


def main():
    OUT.mkdir(exist_ok=True)
    data = {name: read(path) for name, path in SOURCES.items()}
    names = {'baseline': 'Fine-tuning', 'clrr': 'CLRR-only', 'lsr': 'LSR-only', 'full': 'CLRR+LSR'}
    short = {'baseline': 'FT', 'clrr': 'CLRR', 'lsr': 'LSR', 'full': 'Full'}
    s = {(r['method'], r['metric']): r for r in data['summary']}
    table('means', 'lrr', ['Method', 'BLEU', 'chrF++'], [
        [names[m], f(s[m, 'BLEU']['mean']) + r'$\pm$' + f(s[m, 'BLEU']['std_across_seeds']),
         f(s[m, 'chrF++']['mean']) + r'$\pm$' + f(s[m, 'chrF++']['std_across_seeds'])]
        for m in names], 'Fresh matched mBART Amis runs (C): mean and sample standard deviation over seeds 42, 43, and 44. All four methods update all 610,879,488 backbone parameters and add zero parameters.')
    delta_rows = []
    for r in data['deltas']:
        if r['metric'] != 'BLEU':
            continue
        delta_rows.append([short[r['challenger']] + r'$-$' + short[r['baseline']],
                           f(r['seed42']), f(r['seed43']), f(r['seed44']), f(r['mean_delta'])])
    table('seed_deltas', 'lrrrr', ['BLEU difference', '42', '43', '44', 'Mean'], delta_rows,
          'Paired BLEU differences in C. FT is fine-tuning; Full is CLRR+LSR. Full exceeds LSR-only in all three seeds, with a mean increment of 0.2344 BLEU. Per-seed uncertainty is reported in the complete bootstrap table.')
    scores = {r['id']: r for r in data['scores_b']}
    table('backbones', 'llrrr', ['Backbone', 'Method', 'BLEU', 'chrF++', 'chrF'], [
        [model, names[method], f(scores[identifier]['bleu']), f(scores[identifier]['chrfpp']), f(scores[identifier]['chrf0'])]
        for model, method, identifier in [
            ('mBART', 'baseline', 'mbart-baseline'), ('mBART', 'lsr', 'mbart-lsr'), ('mBART', 'full', 'mbart-full'),
            ('NLLB', 'baseline', 'nllb-baseline'), ('NLLB', 'full', 'nllb-full'),
            ('mT5', 'baseline', 'mt5-baseline'), ('mT5', 'clrr', 'mt5-clrr'), ('mT5', 'full', 'mt5-full'),
            ('ByT5', 'baseline', 'byt5-baseline'), ('ByT5', 'full', 'byt5-full')]],
          'Historical Amis checkpoints regenerated under common FP32 inference (B). These are single selected checkpoints, separate from C; their historical training and selection were not fully matched. chrF uses word order 0 and is diagnostic.')
    pairs = [('mBART Full$-$FT', 'mbart-baseline', 'mbart-full'),
             ('mBART Full$-$LSR', 'mbart-lsr', 'mbart-full'),
             ('NLLB Full$-$FT', 'nllb-baseline', 'nllb-full'),
             ('mT5 Full$-$FT', 'mt5-baseline', 'mt5-full'),
             ('mT5 Full$-$CLRR', 'mt5-clrr', 'mt5-full'),
             ('ByT5 Full$-$FT', 'byt5-baseline', 'byt5-full')]
    stats = {(r['baseline'], r['challenger'], r['metric']): r for r in data['bootstrap_b']}
    table('historical_tests', 'lrrr', ['Comparison (B)', r'$\Delta$BLEU', '95\% CI', r'$p_{\rm Holm}$'], [
        [label, f(stats[b, c, 'bleu']['delta']), '[' + f(stats[b, c, 'bleu']['ci_low']) + ',' + f(stats[b, c, 'bleu']['ci_high']) + ']', f(stats[b, c, 'bleu']['p_holm_36'], 4)]
        for label, b, c in pairs], 'Paired sentence bootstrap for B: 10,000 resamples, percentile intervals, Original Holm correction across 36 tests, retained unchanged when reporting the Amis subset. FT denotes full fine-tuning and Full denotes CLRR+LSR. This does not measure uncertainty across training seeds.')
    table('routing', 'lrrrr', ['Dataset/model', 'On', 'Off', r'$\Delta$BLEU', r'$p_{\rm Holm}$'], [
        [label, f(scores[id]['bleu']), f(scores[id+'::route_off']['bleu']), f(stats[id+'::route_off', id, 'bleu']['delta']), f(stats[id+'::route_off', id, 'bleu']['p_holm_36'], 4)]
        for label, id in [('Amis/mBART', 'mbart-full'), ('Amis/NLLB', 'nllb-full'), ('Amis/mT5', 'mt5-full'), ('Amis/ByT5', 'byt5-full')]],
          r'Inference routing sensitivity (B): identical CLRR+LSR weights with $\alpha=0.1$ or 0. Removing a route changes the trained computation and is not a separately trained LSR-only ablation.')
    mech = {r['id']: r for r in data['mechanisms']}
    table('mechanisms', 'lrrrr', ['Dataset/model', r'$r_{FT}$', r'$r_{Full}$', 'Res.\%', 'Grad.\%'], [
        [label, f(mech[base]['source_effective_rank'], 1), f(mech[full]['source_effective_rank'], 1),
         f(100*float(mech[full]['residual_ratio_mean'])), f(100*float(mech[full]['all_parameters_mean_ratio']), 3)]
        for label, base, full in [('Amis/mBART', 'mbart-baseline', 'mbart-full'), ('Amis/NLLB', 'nllb-baseline', 'nllb-full'),
                                ('Amis/mT5', 'mt5-baseline', 'mt5-full'), ('Amis/ByT5', 'byt5-baseline', 'byt5-full')]],
          'Historical selected-checkpoint diagnostics: source effective rank from centered singular-value entropy; mean residual/current RMS ratio; mean weighted LSR/CE gradient norm ratio over eight fixed validation batches. FT auxiliary gradients are counterfactual and not its training objective.')
    rows = []
    for r in data['trajectory']:
        if r['method'] == 'full':
            stage = 'early' if 'early' in r['roles'] else ('middle' if 'middle' in r['roles'] else 'endpoint')
            rows.append([r['seed'], stage, f(r['epoch'], 0), f(100*float(r['weighted_lsr_ce_gradient_ratio_median']), 3),
                         f(100*float(r['encoder_gradient_ratio_median']), 3), f(100*float(r['residual_rms_ratio_mean'])),
                         f(r['source_effective_rank_singular_values'], 1), f(r['target_effective_rank_singular_values'], 1)])
    table('trajectory', 'llrrrrrr', ['Seed', 'Stage', 'Epoch', 'All grad.\%', 'Enc. grad.\%', 'Res.\%', r'$r_s$', r'$r_t$'], rows,
          'Fresh Full trajectories (C). Gradient ratios are medians across eight identical validation batches. Endpoint is the actual training endpoint, not necessarily the validation-selected checkpoint. Singular effective ranks are from all validation sentences. Probes are observational.', wide=True)
    table('individual_seeds', 'rllrr', ['Seed', 'Method', 'Completed epochs', 'BLEU', 'chrF++'], [
        [r['seed'], names[r['method']], f(r['completed_epochs'], 0), f(r['BLEU'], 4), f(r['chrF++'], 4)]
        for r in data['seeds']], 'All 12 fresh matched run results (C). Completed epochs and selected checkpoints are distinct. Baseline seed 42 was recovered from its selected weights; the original selected step is unavailable.', wide=True)
    table('fresh_tests', 'rllrrr', ['Seed', 'Difference', 'Metric', r'$\Delta$', '95\% CI', r'$p_{\rm Holm24}$'], [
        [r['seed'], names[r['challenger']]+r'$-$'+names[r['baseline']], tex(r['metric']), f(r['delta'], 4),
         '['+f(r['ci_low'], 4)+','+f(r['ci_high'], 4)+']', f(r['p_holm24'], 4)]
        for r in data['bootstrap_c']], r'All per-seed corpus bootstrap tests in C. Holm family: four comparisons $\times$ two metrics $\times$ three seeds = 24. None passes corrected $p<0.05$; these tests do not replace inference over training seeds.', wide=True)
    replaced = {('amis_mandarin', model, method) for model, method in [
        ('mBART', 'Baseline'), ('mBART', 'CLRR+LSR'), ('mBART', 'LSR-only'),
        ('NLLB', 'Baseline'), ('NLLB', 'CLRR+LSR'), ('mT5', 'Baseline'), ('mT5', 'CLRR-only'), ('mT5', 'CLRR+LSR'),
        ('ByT5', 'Baseline'), ('ByT5', 'CLRR+LSR')]}
    scoped_a = [r for r in data['audit_a']
                if r['dataset'] == 'amis_mandarin' and r['method'] != 'LayerSkip']
    assert len(scoped_a) == 28
    historical = [r for r in scoped_a
                  if (r['dataset'], r['backbone'], r['method']) not in replaced]
    assert len(historical) == 18
    table('historical_a', 'lllr r', ['Data', 'Backbone', 'Method/checkpoint (A)', 'BLEU', 'chrF++'], [
        ['Amis', r['backbone'], tex(r['method']), f(r['bleu'], 4), f(r['chrfpp'], 4)]
        for r in historical], 'Remaining 18 historical Amis outputs verified from saved predictions (A). These share raw-reference scoring; B standardizes inference on ten other Amis checkpoints. No A/B prediction mixing is used for significance tests.', wide=True)
    manuscript_path = (ROOT / 'docs/paper/clrr_main.tex') if (ROOT / 'docs/paper/clrr_main.tex').exists() else (ROOT / 'docs/clrr_main.tex')
    manuscript, _ = embed_paper_tables(manuscript_path.read_text(encoding='utf-8'))
    manuscript_path.write_text(manuscript, encoding='utf-8')
    provenance = dict(manuscript_sha256=hashlib.sha256(manuscript_path.read_bytes()).hexdigest(),
                      source_files={name: dict(path=path, sha256=hashlib.sha256((ROOT/path).read_bytes()).hexdigest())
                                  for name, path in SOURCES.items()},
                      generated_files={str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(OUT.glob('*.tex'))},
                      protocols={'A': '28 retained Amis outputs from original 36-output audit', 'B': '10 retained Amis FP32 checkpoints + 4 routing-off outputs',
                                 'C': '12 new matched four-branch mBART runs, three seeds'},
                      scope={'dataset': 'amis_mandarin', 'historical_a_remaining': 18,
                             'retained_checkpoint_gradient_batches': 80,
                             'unchanged_original_holm_families': {'A': 42, 'B': 36, 'C': 24}})
    (OUT / 'provenance.json').write_text(json.dumps(provenance, indent=2), encoding='utf-8')
    print(f'Generated {len(provenance["generated_files"])} tables; all source SHA-256 recorded.')


if __name__ == '__main__':
    main()
